name: compass_icon
description: A simple Flutter package to rotate an icon based on different compass directions.
version: 1.0.3+1
repository: https://www.github.com/tytydraco/compass_icon

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true